gallery/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'gallery'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.details, name='details'),
    path('add/', views.add, name='add'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('my_images/', views.my_images, name='my_images'),
    path('<int:image_id>/like_image/', views.like_image, name='like_image'),
    path('<int:image_id>/unlike_image/', views.unlike_image, name='unlike_image'),
    path('liked/', views.liked, name='liked'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('gallery/', include('gallery.urls')),
    path('admin/', admin.site.urls),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from datetime import date
from django.contrib.auth.models import User
from django.utils.timezone import now

from django.db import models

class Image(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1024, null=True, blank=True)
    date = models.DateTimeField(default=now)
    photo = models.ImageField(null=True, blank=True, upload_to='images/')
    popularity = models.IntegerField(default=0)
    owner = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return self.title
    
class Like(models.Model):
    image_id = models.IntegerField(blank=False, default=1)
    user_id = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return "user{0}_likes_image{1}".format(self.user_id, self.image_id)

gallery/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import Image
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'description', 'photo']
        labels = {
            'title': 'Tytuł',
            'description': 'Opis',
            'photo': 'Zdjęcie'
        }
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-input'}),
            'description': forms.Textarea(attrs={'class':'form-input'})
        }


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder':'Login'})
        self.fields['email'].widget.attrs.update({'placeholder':'Email'})
        self.fields['password1'].widget.attrs.update({'placeholder':'Hasło'})
        self.fields['password2'].widget.attrs.update({'placeholder':'Potwierdź hasło'})

        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].label = ''

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("An user with this email already exists!")
        return email

gallery/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from gallery.models import Image, Like
from gallery.forms import ImageForm, RegisterForm


def index(request):
    images_list = Image.objects.order_by('-popularity')
    context = {'images_list': images_list}
    return render(request, 'gallery/index.html', context)

def my_images(request):
    my_images_list = Image.objects.filter(owner=request.user.id).order_by('-date')
    return render(request, 'gallery/my_images.html', {'my_images_list': my_images_list})

def details(request, image_id):
    image = Image.objects.get(pk=image_id)
    liked = False
    image.save()
    if Like.objects.all():
        if Like.objects.filter(image_id=image.id, user_id=request.user.id).exists():
            liked = True
    return render(request, 'gallery/details.html', {'image': image, 'liked': liked})

def like_image(request, image_id):
    l = Like(image_id = image_id, user_id = request.user.id)
    l.save()
    image = Image.objects.get(pk = image_id)
    image.popularity += 1
    image.save()
    return redirect('gallery:details', image_id = image_id)

def unlike_image(request, image_id):
    if Like.objects.filter(image_id = image_id, user_id = request.user.id).exists():
        l = Like.objects.get(image_id = image_id, user_id = request.user.id)
        l.delete()
        image = Image.objects.get(pk = image_id)
        image.popularity -= 1
        image.save()
    return redirect('gallery:details', image_id = image_id)

def liked(request):
    likes_list = Like.objects.filter(user_id=request.user.id)
    images_list = []
    for like in likes_list:
        images_list.append(Image.objects.get(pk=like.image_id))
    return render(request, 'gallery/liked.html', {'images_list': images_list})
    
def add(request):
    submitted = False
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.owner = request.user.id
            image.save()
            return HttpResponseRedirect('/gallery/add?submitted=True')
    else:
        form = ImageForm()
        if 'submitted' in request.GET:
            submitted = True

    return render(request, 'gallery/add.html', {'form':form, 'submitted':submitted})

def signup(request):
    error_text = ''
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            user = authenticate(username=username, password=password1)   
            login(request, user)
            messages.success(request, ("Utworzono konto!"))   
            return redirect('gallery:index') 
    else:
        form = RegisterForm()        
    return render(request, 'gallery/signup.html', {'form': form, 'error_text': error_text})

def signin(request):
    if request.method == 'POST':
        username = request.POST.get('login')
        password1 = request.POST.get('password')
        user = authenticate(username=username, password=password1)
        if user is not None:
            login(request, user)
            return redirect('gallery:index')
        else:
            messages.error(request, "Niepoprawne dane")
    return render(request, 'gallery/signin.html')

def signout(request):
    logout(request)
    return redirect('/gallery/signin/')

gallery/templates/base/base_login.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Galeria zdjęć - logowanie</title>
    {% load static %}
    {% load gallery_extras %}
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
</head>
<body>
    <div class="bg-lines"></div>
    <main>
        <section class="white-box">
            <header>
                <h1>Galeria zdjęć</h1>
            </header>
            <form action="" method="POST">
                {% csrf_token %}
                {% block content %}
                {% endblock %}
            </form>
        </section>
    </main>
</body>
</html>

gallery/templates/base/base_template.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Galeria zdjęć</title>
    {% load static %}
    {% load gallery_extras %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script defer src="{% static 'scripts/navbar.js' %}"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    <header id="navbar">
        <a href="{% url 'gallery:index'%}" class="navbar-elem home">Galeria zdjęć</a>
        <ol class="navbar-list">
            <li><a class="navbar-elem" href="{% url 'gallery:liked' %}">Ulubione</a></li>
            <li><a class="navbar-elem" href="{% url 'gallery:add' %}">Dodaj</a></li>
            <li><a class="navbar-elem" href="{% url 'gallery:my_images' %}">Moje zdjęcia</a></li>
        </ol>
        <nav>
            <ol class="navbar-list">
                {% if user.is_authenticated %}
                <li class="navbar-button"><a href="{% url 'gallery:signout' %}">Wyloguj</a></li>
                {% else %}
                <li class="navbar-button"><a href="{% url 'gallery:signin' %}">Zaloguj się</a></li>
                <li class="navbar-button"><a href="{% url 'gallery:signup' %}">Zarejestruj się</a></li>
            </ol>
            {% endif %}
        </nav>
    </header>

    <div class="container">
        
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

gallery/templates/gallery/add.html
{% extends '../base/base_template.html' %}


{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_add.css' %}">
{% endblock %}
{% block content %}
{% if user.is_authenticated %}

    <div class="wrap">
        <h1 class="page-title">Dodaj obraz</h1>
        <br><br>
        {% if submitted %}
            Pomyślnie dodano zdjęcie!
        {% else %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}

                <input type="submit" class="form-submit" value="Dodaj"></input>
            </form>
        {% endif %}
    </div>
{% else %}
    <div class="logged-out">
        <h1>Zaloguj się aby dodać zdjęcie</h1>
    </div>
{% endif %}
{% endblock %}

gallery/templates/gallery/details.html
{% extends '../base/base_template.html' %}



{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_details.css' %}">
{% endblock %}
{% block content %}
        <div class="element-img">
            <img src="{{ image.photo.url }}" alt="krajobraz">
        </div>
        <div class="element-description">
            <h1>{{ image.title }}</h1>
            <div>{{ image.description }}</div>
                {% if user.is_authenticated %}
                    {% if liked %}
                    <a class="like-button full" href="{% url 'gallery:unlike_image' image.id %}"></a>
                    {% else %}
                    <a class="like-button empty" href="{% url 'gallery:like_image' image.id %}"></a>
                    {% endif %}
                {% else %}
                <a class="like-button empty" href="{% url 'gallery:signin' %}"></a>
                {% endif %}
                <p class="image-popularity">{{ image.popularity }}</p>
        </div>
{% endblock %}

gallery/templates/gallery/index.html
{% extends '../base/base_template.html' %}


{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_content.css' %}">
{% endblock %}
{% block content %}
    {% if images_list %}
    <h1 class="page-title">Strona główna</h1>
        {% for image in images_list %}
            <a href="{% url 'gallery:details' image.pk %}">
                <div class="element" id="{{ image.title }}">
                    <img class="item" src="{{ image.photo.url }}" alt="krajobraz">
                </div>
            </a>
        {% endfor %}
    {% endif %}
{% endblock %}

gallery/templates/gallery/liked.html
{% extends '../base/base_template.html' %}

{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_content.css' %}">
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    {% if images_list %}
    <h1 class="page-title">Ulubione zdjęcia</h1>
        {% for image in images_list %}
            <a href="{% url 'gallery:details' image.id %}">
                <div class="element" id="{{ image.title }}">
                    <img class="item" src="{{ image.photo.url }}" alt="krajobraz">
                </div>
            </a>
        {% endfor %}
    {% endif %}
{% else %}
    <div>
        <h1>Zaloguj się aby przeglądać ulubione zdjęcia</h1>
    </div>
{% endif %}
{% endblock %}

gallery/templates/gallery/my_images.html
{% extends '../base/base_template.html' %}

{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_content.css' %}">
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    {% if my_images_list %}
    <h1 class="page-title">Moje zdjęcia</h1>
        {% for my_image in my_images_list %}
            <a href="{% url 'gallery:details' my_image.id %}">
                <div class="element" id="{{ my_image.title }}">
                    <img class="item" src="{{ my_image.photo.url }}" alt="krajobraz">
                </div>
            </a>
        {% endfor %}
    {% endif %}
{% else %}
    <div>
        <h1>Zaloguj się aby przeglądać dodane przez siebie zdjęcia</h1>
    </div>
{% endif %}
{% endblock %}

gallery/templates/gallery/signin.html
{% extends '../base/base_login.html' %}


{% block content %}
    <input type="text" placeholder="Login" id="login" name="login"/>
    <input type="password" placeholder="Hasło" id="password" name="password"/>
    <button type="submit" id="loginButton" name="loginButton">Zaloguj</button>
    <a href="#">Nie pamiętasz hasła?</a>
    <a href="{% url 'gallery:signup' %}">Stwórz konto</a>
{% endblock %}

gallery/templates/gallery/signup.html
{% extends '../base/base_login.html' %}


{% block content %}
    {% csrf_token %}
    {{ form }}
    <button type="submit" id="signupButton" name="signupButton">Zarejestruj</button>
    <a href="{% url 'gallery:signin' %}">Masz już konto?</a>
    {% if form.errors %}
    <p>Błąd</p>
    {% endif %}
{% endblock %}